name: First Workflow
on:
  push:
  pull_request:
    branches: ['**']     # any target branch
    paths: ['**']        # any files changed
    types: [opened, synchronize, reopened, ready_for_review]
 
 
 
  workflow_dispatch:
 
  #MIN HOUR DAY MONTH WEEKDAY
  #12:00 IST → 06:30 UTC → cron: '30 6 * * *'
  # schedule:
  #   # Daily at 09:00 IST (UTC+5:30) -> 03:30 UTC
  #   - cron: '30 3 * * *'
permissions:
  contents: write

jobs:
  Prod-approver:
    name: Reviewer Approval
    runs-on: ubuntu-latest
    environment: Prod Approval
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Request is sended
        run: |
          echo "Waiting for approver to approve this request"
  TimeZone-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create folder
        run: |
          if [ -d "textfolder" ]; then
            echo "File and Folder Exist!"
          else
            mkdir -p textfolder
            echo "This file contains zone time, date and event"> textfolder/timestamp.txt
            echo "File and Folder Created Successfully!"
          fi

      - name: Write timestamp and event info
        run: |
          export TZ="Asia/Kolkata"
          NOW="$(date '+%Y-%m-%d %H:%M:%S %Z')"
          echo "--------------------------------------------------------" >> textfolder/timestamp.txt
          echo "Event: ${{ github.event_name}}" >> textfolder/timestamp.txt
          echo "Repository: ${{ github.repository}}" >> textfolder/timestamp.txt
          echo "Branch: ${{ github.ref_name}}" >> textfolder/timestamp.txt
          echo "Changed file(s): ${CHANGED_FILES}" >> textfolder/timestamp.txt
          echo "Triggered at (IST): ${NOW}" >> textfolder/timestamp.txt
          echo "--------------------------------------------------------" >> textfolder/timestamp.txt

      - name: Commit changes
        run: |
          git config user.name "ani002agarwal"
          git config user.email "ankit.garg1.ext@bayer.com"
 
          git add textfolder/timestamp.txt
          git commit -m "Update timestamp from ${{github.event_name}}" || echo "No Commit"
          git push
          
  first-job:
   runs-on: ubuntu-latest
   steps:
     - name: print greeting
       run:  echo "Hello world!"
     - name: print by
       run: echo "Done by"
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: print Dev Environment Variable
        run: |
          echo "Dev Variable 1= ${{vars.variable1}}"
          echo "secret Variable= ${{secrets.passkey}}"

  Test:
    runs-on: ubuntu-latest
    needs: [Dev]
    environment: Test
    steps:
      - name: print Test environment Variable
        run: |
          echo "Test Variable 1=${{vars.variable1}}"

  Prod:
   runs-on: ubuntu-latest
   needs: [Prod-approver,Test]
   environment: Prod
   steps:
     - name: print Prod Environment variable
       run: |
         echo "Prod Variable 1= ${{vars.variable1}}"
         echo "secret Variable= ${{secrets.privacy}}"
      

      
     
      
     
   
  
